extensions:
    wissend-settings-index:
        module: pim/common/simple-view
        aclResourceId: wissend_settings
        config:
            template: pim/template/common/default-template

    wissend-settings-index-grid-container:
        module: pim/common/simple-view
        parent: wissend-settings-index
        targetZone: content
        config:
            template: pim/template/form/index/index

    wissend-settings-index-user-navigation:
        module: pim/menu/user-navigation
        parent: wissend-settings-index
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout: pim_menu.user.logout

    wissend-settings-index-grid-title:
        module: pim/common/grid-title
        parent: wissend-settings-index
        targetZone: title
        config:
            countable: false
            title: Wissend Settings

    wissend-settings-index-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: wissend-settings-index
        targetZone: breadcrumbs
        config:
            tab: pim-menu-wissend-settings  