extensions:
    pim-menu-wissend-dashboard:
        module: pim/menu/item
        parent: pim-menu-activity-navigation-block
        position: 113
        aclResourceId: wissend_dashboard
        config:
            title: pim_menu.item.wissend_dashboard
            to: wissend_dashboard

    pim-menu-wissend-settings:
        module: pim/menu/tab
        parent: pim-menu
        position: 80
        targetZone: mainMenu
        aclResourceId: wissend_settings
        config:
            title: pim_menu.item.wissend_settings
            iconModifier: iconSettings
            to: wissend_settings

            