services:
  wissend.custom_bundle.mass_edit_action.operation.capitalize_values:
    public: false
    class: Wissend\Bundle\CustomBundle\MassEditAction\Operation
    arguments:
      - 'mass_edit_capitalize_values'
    tags:
      -
        name: pim_enrich.mass_edit_action
        alias: capitalize-values
        acl: pim_enrich_product_edit_attributes
        datagrid: product-grid
        operation_group: mass-edit
        form_type: acme_custom_mass_action_operation_capitalize_values 

