services:
    wissend.step.add_comment.mass_edit:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'perform'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_enrich.reader.database.product_and_product_model'
            - '@wissend.custom.connector.processor.mass_edit.product'
            - '@pim_connector.writer.database.product'

    wissend_custom.step.capitalize_values.mass_edit:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'mass_edit_capitalize_values'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_connector.reader.database.product'
            - '@wissend_custom.mass_edit.capitalize_values.processor'
            - '@pim_connector.writer.database.product'        